nkmk<br>
https://note.nkmk.me/python-sklearn-train-test-split/<br>
<br>
Official<br>
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
x = np.arange(10).reshape((5, 2))
y = list(range(5))

print(x)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [4]:
# Apply on x and y simualtaniously
# Can apply on np.array, list, pd.DataFrame
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4,)

In [5]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[8 9]
 [6 7]
 [4 5]]
[[0 1]
 [2 3]]
[4, 3, 2]
[0, 1]
